# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-UTV
version:      0.02
version_from: lib/Business/UTV.pm
installdirs:  site
requires:
    Gtk2::TrayIcon:                0
    LWP:                           0
    Net::SSLeay:                   0
    POSIX:                         0
    Test::MockObject:              0
    Test::NoWarnings:              0
    Test::Warn:                    0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
